name: CI - Build, Test, and Docker Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gen-com-services-ci:
    name: gen-com-services - Build, Test & Docker Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install gen-com-services Dependencies
        run: |
          cd gen-com-services
          pip install --no-cache-dir -r requirements.txt

      - name: Run gen-com-services Tests
        run: |
          cd gen-com-services
          pytest --disable-warnings

      - name: Docker Build gen-com-services
        run: |
          cd gen-com-services
          docker build -t gen-com-services:latest .

  gen-com-ui-ci:
    name: gen-com-ui - Build, Test & Docker Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install gen-com-ui Dependencies
        run: |
          cd gen-com-ui
          npm install

      - name: Run Linter
        run: |
          cd gen-com-ui
          npm run lint

      - name: Run gen-com-ui Tests
        run: |
          cd gen-com-ui
          npm test

      - name: Build gen-com-ui
        run: |
          cd gen-com-ui
          npm run build

      - name: Docker Build gen-com-ui
        run: |
          cd gen-com-ui
          docker build -t gen-com-ui:latest .
