name: CI/CD Pipeline - GenCommerce with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run-services:
    name: Build & Run gen-com-services and gen-com-ui with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: |
          docker build -t gen-com-services ./gen-com-services
          docker build -t gen-com-ui ./gen-com-ui

      - name: Run Docker Containers
        run: |
          docker network create gencommerce-network

          docker run -d --name gen-com-services \
            --network gencommerce-network \
            -p 8000:8000 gen-com-services

          docker run -d --name gen-com-ui \
            --network gencommerce-network \
            -p 3000:3000 gen-com-ui

      - name: Check Running Containers
        run: docker ps

      - name: Run Backend Tests (gen-com-services)
        run: docker exec gen-com-services pytest

      - name: Run Frontend Tests (gen-com-ui)
        run: docker exec gen-com-ui npm run test

      - name: Stop Containers
        if: always()
        run: |
          docker stop gen-com-services gen-com-ui
          docker rm gen-com-services gen-com-ui
