name: CI/CD Pipeline - GenCommerce

on:
  push:
    branches:
      - main

jobs:
  test-lint-build-gen-com-services:
    name: Test & Lint gen-com-services (gen-com-services)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd gen-com-services
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: |
          cd gen-com-services
          pip install flake8
          flake8 . --exclude=venv,__pycache__ --max-line-length=88

      # - name: Run Tests
      #   run: |
      #     cd gen-com-services
      #     pip install pytest
      #     pytest

  test-lint-build-gen-com-ui:
    name: Test & Lint gen-com-ui
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd gen-com-ui
          npm install

      - name: Lint with ESLint
        run: |
          cd gen-com-ui
          npm run lint

      - name: Run Tests
        run: |
          cd gen-com-ui
          npm run test

      - name: Build Project
        run: |
          cd gen-com-ui
          npm run build

  # deploy-gen-com-services:
  #   name: Deploy gen-com-services (gen-com-services)
  #   runs-on: ubuntu-latest
  #   needs: test-lint-build-gen-com-services

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.9"

  #     - name: Install dependencies
  #       run: |
  #         cd gen-com-services
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Package FastAPI app
  #       run: |
  #         cd gen-com-services
  #         zip -r deploy.zip . -x "*.git*"

  #     - name: Deploy to AWS Lambda
  #       uses: aws-actions/aws-lambda-deploy@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}
  #         function-name: "gen-com-services"
  #         zip-file: "gen-com-services/deploy.zip"

  # deploy-gen-com-ui:
  #   name: Deploy gen-com-ui (gen-com-ui)
  #   runs-on: ubuntu-latest
  #   needs: [test-lint-build-gen-com-ui, deploy-gen-com-services]

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Install Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"

  #     - name: Install dependencies
  #       run: |
  #         cd gen-com-ui
  #         npm install

  #     - name: Build Next.js app
  #       run: |
  #         cd gen-com-ui
  #         npm run build && npm run export

  #     - name: Deploy to S3
  #       run: |
  #         aws s3 sync gen-com-ui/out s3://your-bucket-name --delete
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_REGION: ${{ secrets.AWS_REGION }}

  #     - name: Invalidate CloudFront cache
  #       run: |
  #         aws cloudfront create-invalidation --distribution-i
